[package]
name = "avatar_ai"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
storm-core = { path = "../../crates/storm-core" }
tokio = { workspace = true, features = ["full"] }
serde.workspace = true
anyhow.workspace = true
